baseURL = 'https://yochem.nl'
languageCode = 'en-us'
title = 'Yochem'
disableKinds = ['taxonomy', 'term']
minify = true
uglyURLs = true

[outputFormats]
	[outputFormats.PLAIN]
		baseName = 'index'
		isPlainText = true
		mediaType = 'text/plain'
		suffixes = ['txt']

[outputs]
	home = ['HTML', 'MARKDOWN']
	page = ['HTML', 'MARKDOWN', 'PLAIN']

[markup.goldmark]
	[markup.goldmark.extensions]
		strikethrough = true
